export { default as Navbar} from './page/Navbar'
export { default as Footer } from './page/Footer'
export { default as RentPage } from './page/RentPage'
export { default as BuyPage } from './page/BuyPage'
export { default as AboutPage} from './page/AboutPage'